Johnha/feature/create unavailability testing
TechlauncherFireApp/backend pull request #174
Opened 2024-03-10 07:02 UTC by TaiHaDev

## Describe your changes
Setting up a testing environment for the project using pytest. Creating testing folders for functional and unit testing. Needed to be further refined to have development, testing, and production configuration. Currently, testing will create and get directly from the database which is not a good practice. Creating some test cases for creating unavailability endpoint with testing criteria: 
- two consecutive create operations must output two consecutive event_id
- Cannot create two unavailability with the same time interval
- Cannot create availability for nonexistent user_id
- Cannot create unavailability with an end time earlier than the start time
- Cannot create unavailability with weird periodicity (to be discussed)
- There cannot be two unavailability from the same user with overlapped time interval
- Merge interval (if implemented on API)

Some significant changes:
- Creating a tests folder that will contain all future functional and unit tests for the project
- Refactoring application.py class to make use of factory method design pattern so that many instances of the application can be created, for now, it can be used in testing
<img width="467" alt="image" src="https://github.com/TechlauncherFireApp/backend/assets/97883232/f9ee0b5a-ad7a-469c-8d4e-fbea15e3f0f9">

## Issue ticket number and link
https://fireapp-emergiq-2024.atlassian.net/jira/software/projects/FE/boards/1?selectedIssue=FE-68

2024-03-10 11:46 UTC, BenMMcLean requested changes
In the future we should be writing our repositories etc such that we can do proper unit testing, but this is a good effort considering the code you were given!

Address the minor feedback, and remove the underscores from your branch name, just use dashes "-".

2024-03-11 08:36 UTC, TaiHaDev commented on services/optimiser/input_processing.py
> +# This can be called by api from postman, to tests easily
Yeah, I wanted to ask you about that in the meeting yesterday. All the tests written before seem to be useless, and they also wrote them within the same file as the logic code. Maybe we can discuss deleting them?
<img width="507" alt="image" src="https://github.com/TechlauncherFireApp/backend/assets/97883232/602966cc-1c33-45c7-8b2a-195962faf902">

2024-03-12 05:41 UTC, TaiHaDev commented
Hi @BenMMcLean , can you have a look at my comment and my changes :-) thank youu

2024-03-12 06:57 UTC, BenMMcLean commented on services/optimiser/input_processing.py
> +# This can be called by api from postman, to tests easily
Yep deleting them is fine with me

2024-03-12 06:58 UTC, BenMMcLean commented on controllers/v2/unavailability/api.py
> -    @requires_auth
No worries :)

2024-03-12 06:59 UTC, BenMMcLean submitted a review, later dismissed

2024-03-12 13:19 UTC, TaiHaDev commented
I tried to pull request pr-174 in Git but I think you meant something else cause I didn't find anything after pulling. It would be very helpful if you can show me some resources related to this cause I have no previous knowledge about this Github ci/cd. However, I still managed to fix the error :-) It happened because I refactored `application.py` into using factory method. I basically reverted the changes, I don't know exactly why it happened as the logic should be the same and it didn't really break anything as far as I can see.

2024-03-12 13:31 UTC, TaiHaDev commented
Some new changes:
- adding more testing fixtures to get JWT token and append to all testing requests so that they are authorised
- only using one application instance for all test cases
Some drawbacks that I need to discuss with you:
- I think we need a testing environment (using in-memory database) but I think it maybe out of the project's scope
- cannot create new application instance for testing can be fine for now but maybe hard to implement the above suggestion
Thanks for your time ☺️

2024-03-12 22:52 UTC, BenMMcLean commented
There aren't any resources AFAIK, but all you have to do to run the docker image of your code is modify the docker-compose.frontend.yml file, changing 
`docker pull ghcr.io/techlauncherfireapp/backend:latest` to `docker pull ghcr.io/techlauncherfireapp/backend:pr-<your pr number>`, and running the file.

2024-03-12 22:53 UTC, BenMMcLean approved these changes
Looks good to me!

2024-03-13 00:50 UTC, merged